// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAps8V2LS3al7mdDQtFUHv2H01_R5fkWvg',
    appId: '1:532373173517:web:65eee70b951968ff57ac44',
    messagingSenderId: '532373173517',
    projectId: 'sks-alibi',
    authDomain: 'sks-alibi.firebaseapp.com',
    storageBucket: 'sks-alibi.firebasestorage.app',
    measurementId: 'G-LVGDM8NK67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT1bqUSEuQpa_lauBaaJcTpm7CLFo9vE0',
    appId: '1:532373173517:android:aadc79a59098bd0b57ac44',
    messagingSenderId: '532373173517',
    projectId: 'sks-alibi',
    storageBucket: 'sks-alibi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3XlSQHbQCnmAR1jA7ZjFoPVU9vV7j5B8',
    appId: '1:532373173517:ios:d3f4984c6f640f7e57ac44',
    messagingSenderId: '532373173517',
    projectId: 'sks-alibi',
    storageBucket: 'sks-alibi.firebasestorage.app',
    iosBundleId: 'com.sks.sksAlibi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3XlSQHbQCnmAR1jA7ZjFoPVU9vV7j5B8',
    appId: '1:532373173517:ios:d3f4984c6f640f7e57ac44',
    messagingSenderId: '532373173517',
    projectId: 'sks-alibi',
    storageBucket: 'sks-alibi.firebasestorage.app',
    iosBundleId: 'com.sks.sksAlibi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAps8V2LS3al7mdDQtFUHv2H01_R5fkWvg',
    appId: '1:532373173517:web:052a5760ba26ff1857ac44',
    messagingSenderId: '532373173517',
    projectId: 'sks-alibi',
    authDomain: 'sks-alibi.firebaseapp.com',
    storageBucket: 'sks-alibi.firebasestorage.app',
    measurementId: 'G-M9KYDX4RB6',
  );
}
