name: Build Android APK

on:
  push:
    branches: [ "**" ]   # build
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      # ---- DEBUG & GUARD ----
      - name: Debug repo & guard files
        run: |
          echo "Branch:" && git rev-parse --abbrev-ref HEAD || true
          echo "== ROOT ==" && ls -la
          echo "== app ==" && ls -la app || true
          echo "== app/src ==" && ls -la app/src || true
          echo "== app/src/main ==" && ls -la app/src/main || true

          # Vérifie la présence du Manifest
          if [ -f app/src/main/AndroidManifest.xml ]; then
            echo "Manifest present: YES"
            sed -n '1,80p' app/src/main/AndroidManifest.xml || true
          else
            echo "Manifest present: NO -> creating minimal one"
            mkdir -p app/src/main
            cat > app/src/main/AndroidManifest.xml <<'EOF'
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.sks.alibi">
    <application
        android:label="@string/app_name"
        android:theme="@style/Theme.SKSAlibi">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
EOF
          fi

          # Vérifie layout
          if [ ! -f app/src/main/res/layout/activity_main.xml ]; then
            echo "Missing layout -> create minimal"
            mkdir -p app/src/main/res/layout
            cat > app/src/main/res/layout/activity_main.xml <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <TextView
        android:id="@+id/hello"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello SKS Alibi"
        android:textSize="20sp"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"/>
</androidx.constraintlayout.widget.ConstraintLayout>
EOF
          fi

          # Vérifie strings
          if [ ! -f app/src/main/res/values/strings.xml ]; then
            echo "Missing strings -> create"
            mkdir -p app/src/main/res/values
            cat > app/src/main/res/values/strings.xml <<'EOF'
<resources>
  <string name="app_name">SKS Alibi</string>
</resources>
EOF
          fi

          # Vérifie theme
          if [ ! -f app/src/main/res/values/themes.xml ]; then
            echo "Missing themes -> create"
            mkdir -p app/src/main/res/values
            cat > app/src/main/res/values/themes.xml <<'EOF'
<resources>
  <style name="Theme.SKSAlibi" parent="Theme.Material3.DayNight.NoActionBar"/>
</resources>
EOF
          fi

          # Vérifie MainActivity.java (Java pour éviter Kotlin config)
          if [ ! -f app/src/main/java/com/sks/alibi/MainActivity.java ]; then
            echo "Missing MainActivity -> create"
            mkdir -p app/src/main/java/com/sks/alibi
            cat > app/src/main/java/com/sks/alibi/MainActivity.java <<'EOF'
package com.sks.alibi;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
public class MainActivity extends AppCompatActivity {
  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
  }
}
EOF
          fi

      - name: Build Debug APK
        run: gradle --no-daemon clean :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
